spring.application.name=ebs
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ebs
spring.datasource.username=postgres
spring.datasource.password=1
spring.liquibase.change-log=db/changelog/main-changelog.xml

frequency=1
period=30

jms.queue=book_queue

spring.artemis.mode=native
spring.artemis.user=admin
spring.artemis.password=test

spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=expansi0@mail.ru
spring.mail.password=4dZec8pMgKyk9e0NDxAz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true